[package]
name = "i3wm_switch_windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-i3ipc = "0.16.0"
tokio = "1.37.0"